In [43]:
#building Ml model for breast cancer data
# importing the libraries
import numpy as np
import pandas as pd
import math


In [33]:
df = pd.read_csv("/content/breast-cancer-wisconsin.csv", header = None)

In [34]:
df.head()

0   1   2   3   4   5     6   7   8   9   10
0  1000025   5   1   1   1   2   1.0   3   1   1   2
1  1002945   5   4   4   5   7  10.0   3   2   1   2
2  1015425   3   1   1   1   2   2.0   3   1   1   2
3  1016277   6   8   8   1   3   4.0   3   7   1   2
4  1017023   4   1   1   3   2   1.0   3   1   1   2

In [35]:
df = df.dropna()

In [36]:
df.shape

(683, 11)

In [37]:
x = df.iloc[:,:10].values
y = df.iloc[:,10:].values

In [38]:
x

array([[1.000025e+06, 5.000000e+00, 1.000000e+00, ..., 3.000000e+00,
        1.000000e+00, 1.000000e+00],
       [1.002945e+06, 5.000000e+00, 4.000000e+00, ..., 3.000000e+00,
        2.000000e+00, 1.000000e+00],
       [1.015425e+06, 3.000000e+00, 1.000000e+00, ..., 3.000000e+00,
        1.000000e+00, 1.000000e+00],
       ...,
       [8.888200e+05, 5.000000e+00, 1.000000e+01, ..., 8.000000e+00,
        1.000000e+01, 2.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 1.000000e+01,
        6.000000e+00, 1.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 1.000000e+01,
        4.000000e+00, 1.000000e+00]])

In [39]:
y

array([[2],
       [2],
       [2],
       [2],
       [2],
       [4],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [4],
       [2],
       [4],
       [4],
       [2],
       [2],
       [4],
       [2],
       [4],
       [4],
       [2],
       [2],
       [4],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [4],
       [2],
       [2],
       [2],
       [4],
       [2],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [2],
       [4],
       [2],
       [2],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [2],
       [4],
       [4],
       [2],
       [4],
       [2],
       [4],
       [4],
       [2],
       [2],
       [4],
       [2],
       [4],
       [4],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [4],
    

In [40]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [41]:
#Split the data into 80% training and 20% testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20) 

In [42]:
#Create the models
#Create the 1inear regression model
lr = LinearRegression().fit(x_train, y_train)

In [45]:
#Show the model linear regression prediction
lr_prediction = lr.predict(x_test)
print(lr_prediction)

[[4.16337844]
 [3.64414836]
 [1.93391308]
 [2.00363673]
 [4.6090404 ]
 [4.33305677]
 [2.17538884]
 [2.00118482]
 [2.24056827]
 [3.81071241]
 [2.29140538]
 [1.92902438]
 [2.36991057]
 [3.15331207]
 [2.25748506]
 [2.84647105]
 [1.97822517]
 [1.91438558]
 [3.33923634]
 [4.03521152]
 [3.65892319]
 [2.04806975]
 [1.86235552]
 [3.58831459]
 [2.69542809]
 [1.89442484]
 [2.0958702 ]
 [1.86007855]
 [2.03580485]
 [3.55399819]
 [2.29855246]
 [1.95773418]
 [2.04930865]
 [2.07606152]
 [1.89680466]
 [1.8439055 ]
 [2.10268557]
 [2.24119797]
 [3.46119351]
 [2.12872993]
 [2.04644032]
 [1.85477987]
 [1.99025608]
 [4.12450496]
 [2.03248731]
 [2.11334929]
 [2.87595379]
 [1.95782116]
 [3.80962646]
 [3.31072647]
 [2.06425641]
 [1.92952718]
 [3.78830601]
 [2.30984727]
 [1.88291627]
 [3.34419208]
 [2.2797666 ]
 [1.98154367]
 [3.18158899]
 [2.05389342]
 [3.92013972]
 [3.19899878]
 [3.9756974 ]
 [3.78205384]
 [2.13521786]
 [2.18958067]
 [2.16671434]
 [3.98036557]
 [2.12327615]
 [1.91858885]
 [3.77759879]
 [3.89

In [46]:
mse = mean_squared_error(lr_prediction,y_test)

rmse = math.sqrt(mse)

print(rmse)

0.37943659907010957
